name: spanish_bear_curator
channels:
  - fastai
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - pytorch>=1.2.0
  - fastai=2.0.8
  - matplotlib
  - pandas
  - seaborn
  - requests
  - packaging
  - pillow
  - python>=3.6
  - pip
  - voila
  - ipywidgets==7.5.1
